try...catch...finally代码块执行顺序

//异常被捕获的情况
1.如果try中某条语句发生异常，那么语句后面的代码不会被执行，程序直接跑到catch处执行,catch块中代码全部会执行
2.finally中代码一定会执行，finally代码执行完后，仍然会执行该方法后面的代码
3.如果在catch代码末尾处有reuturn语句,finally语句仍会执行，但该 方法后面的代码不会被执行到。
4.只有一种情况finally不会被执行：catch中调用了System.exit()方法。当然，该 方法后面的代码也不会被执行到
5.如果内存捕获后，直接抛出(通过throw方式)，则除了finally代码块，该方法后面的代码均不会被执行到。

//异常未被捕获的情况：即没有进行异常捕获的情况，这时候根本没有try...catch...finally代码
对于RunntimeException，发现异常后，该方法后面的代码都不会得到执行。
